# Generated by Django 6.0 on 2025-12-05 16:49

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregions',
            name='name_ge',
            field=models.CharField(max_length=50, validators=[main_app.models.validate_not_whitespace], verbose_name='რეგიონის დასახელება'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='name_ge',
            field=models.CharField(max_length=50, validators=[main_app.models.validate_not_whitespace], verbose_name='რეგიონის დასახელება'),
        ),
    ]
