# Generated by Django 6.0 on 2025-12-06 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_districts_historicaldistricts'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='main_app.regions', verbose_name='რეგიონი'),
        ),
        migrations.AddField(
            model_name='historicaldistricts',
            name='region',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main_app.regions', verbose_name='რეგიონი'),
        ),
        migrations.AlterField(
            model_name='districts',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შეიქმნა'),
        ),
        migrations.AlterField(
            model_name='districts',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='განახლდა'),
        ),
        migrations.AlterField(
            model_name='historicaldistricts',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='შეიქმნა'),
        ),
        migrations.AlterField(
            model_name='historicaldistricts',
            name='updated',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='განახლდა'),
        ),
        migrations.AlterField(
            model_name='historicalregions',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='შეიქმნა'),
        ),
        migrations.AlterField(
            model_name='historicalregions',
            name='updated',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='განახლდა'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შეიქმნა'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='განახლდა'),
        ),
    ]
