# Generated by Django 6.0 on 2025-12-06 22:36

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_districts_region_historicaldistricts_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districts',
            name='name_ge',
            field=models.CharField(max_length=50, unique=True, validators=[main_app.models.validate_not_whitespace], verbose_name='რაიონის/ქალაქის დასახელება'),
        ),
        migrations.AlterField(
            model_name='historicaldistricts',
            name='name_ge',
            field=models.CharField(db_index=True, max_length=50, validators=[main_app.models.validate_not_whitespace], verbose_name='რაიონის/ქალაქის დასახელება'),
        ),
        migrations.AlterField(
            model_name='historicalregions',
            name='name_ge',
            field=models.CharField(db_index=True, max_length=50, validators=[main_app.models.validate_not_whitespace], verbose_name='რეგიონის დასახელება'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='name_ge',
            field=models.CharField(max_length=50, unique=True, validators=[main_app.models.validate_not_whitespace], verbose_name='რეგიონის დასახელება'),
        ),
    ]
