# Generated by Django 6.0 on 2025-12-06 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_districts_name_ge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districts',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='main_app.regions', verbose_name='რეგიონი'),
        ),
        migrations.AlterField(
            model_name='historicaldistricts',
            name='region',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main_app.regions', verbose_name='რეგიონი'),
        ),
    ]
